In [1]:
import pandas as pd

data = pd.read_csv('labeled_comments.txt', sep='\t', header=None, names=['org_label', 'text'])
label_map = {'n': 0, 'p': 1, '0': 2}
data['label'] = data['org_label'].map(label_map)
data

     org_label                                               text  label
0            0                                         co se děje      2
1            n  Jsem z nich na prášky...:-D :D ... se divím , ...      0
2            p                        Nejlepší bylo Bounty... :-)      1
3            0      :D Já jsem četla: z vlaku vypadl kluk Ruda :D      2
4            0                       a budou venku i v neděly?=O]      2
...        ...                                                ...    ...
8747         0                                  ne al chtěla bych      2
8748         n  vidim že O2 řeší problemy tím, že smaže diskus...      0
8749         0                              ale koupili jsme ! :P      2
8750         0       Dobrý den, tel. číslo je 723 735 749. Děkuji      2
8751         p  Nádherný! Jako by jasně říkal:"sem zmoklej a c...      1

[8752 rows x 3 columns]

In [ ]:
data.to_csv('./editedlabels.csv')